export const STATUS_OK = 200;
export const STATUS_CREATED = 201;
export const STATUS_MOVED_PERMANENTLY = 301;
export const STATUS_TEMPORARY_REDIRECT = 307;
export const STATUS_BAD_REQUEST = 400;
export const STATUS_FORBIDDEN = 403;
export const STATUS_NOT_FOUND = 404;
export const STATUS_INTERNAL_SERVER_ERROR = 500;
export const STATUS_BAD_GATEWAY = 502;
export const STATUS_SERVICE_UNAVAILABLE = 503;
export const STATUS_GATEWAY_TIMEOUT = 504;


