GET {{offlineURL}}/hi
Accept: */*
Cache-Control: no-cache
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTYiLCJuYW1lIjoiSm9obiBEb2UiLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNTE2MjM5MDIyfQ.lAQH7nObwxhWTLRPoy21Jjk2tCkPg42vFb5XzOk4KUETxTZgoevm9Nv-PcoT10FRrm9Rzq-QZyvCGNFDVM1rCzdyfiy_AdOOiBwCgcLDMq1Qwi4ut56M6Rb2SfqZsLIDOiTHbtID3hSl1_YXIKbDVy8_sUAUh0e4s2WTivlHwKhMiAjo5fpU2JZm-UFwjIu-Z4edthcLN1cvmXDUW-N7OsIVf9yNDE1WZwGgeL23LJNz3nNMVmDiWBPeXfVkbArf7O0c1NCTo5SS7Z8fRYhTH9fW04BD8I53nlwnTnsQNljL1lG2TJQyEupJig2WEMkfwjhZCg7y7dRkkW_PBlLd4A

<> 2020-06-15T121211.200.json

###

GET {{offlineURL}}/hello
Accept: */*
Accept-Encoding: gzip, deflate, br
Authorization: Bearer 123


### Create an user with username passwd
POST {{offlineURL}}/create
Authorization: Bearer 123
Content-Type: application/json

{
  "ts": {{$timestamp}},
  "email": "nsd@google.com",
  "password": "pwd12344"
}

### Create duplicate account to get error
POST {{offlineURL}}/create
Authorization: Bearer 123
Content-Type: application/json

{
  "ts": {{$timestamp}},
  "email": "nsd@grr.la",
  "password": "pwd123"
}


### email not present in request
POST {{offlineURL}}/create
Authorization: Bearer 123
Content-Type: application/json

{
  "ts": {{$timestamp}},
  "password": "pwd123123"
}


### email & password not present in request
POST {{offlineURL}}/create
Authorization: Bearer 123
Content-Type: application/json

{
  "ts": {{$timestamp}}
}

### email misformed
POST {{offlineURL}}/create
Authorization: Bearer 123
Content-Type: application/json

{
  "email": "thisEmailShouldGiveError"
}
