### Create an user with username password: Success
POST {{offlineURL}}/create
Authorization: Bearer 123
Content-Type: application/json

{
  "ts": {{$timestamp}},
  "email": "nsd@google.com",
  "password": "pwd12344"
}

### Create duplicate account: Error
POST {{offlineURL}}/create
Authorization: Bearer 123
Content-Type: application/json

{
  "ts": {{$timestamp}},
  "email": "nsd@grr.la",
  "password": "pwd123"
}


### Email not present in request: Error
POST {{offlineURL}}/create
Authorization: Bearer 123
Content-Type: application/json

{
  "ts": {{$timestamp}},
  "password": "pwd123123"
}


### Email & password not present in request: Error
POST {{offlineURL}}/create
Authorization: Bearer 123
Content-Type: application/json

{
  "ts": {{$timestamp}}
}

### Email ill-formed: Error
POST {{offlineURL}}/create
Authorization: Bearer 123
Content-Type: application/json

{
  "ts": {{$timestamp}},
  "email": "thisEmailShouldGiveError"
}
