service:
  name: leetcode-timer

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler
  AuthJWT:
    handler: src/lambda/auth/rs256Authorizer.handler
  hello:
    handler: src/lambda/http/helloWorld.handler
    events:
      - http:
          method: get
          path: hello
          cors: true
          authorizer: Auth
  hi:
    handler: src/lambda/http/hi.handler
    events:
      - http:
          method: get
          path: hi
          cors: true
          authorizer: AuthJWT
  dashboard:
    handler: src/lambda/http/dashboard.handler
    events:
      - http:
          method: get
          path: dashboard
          cors: true
          authorizer: AuthJWT
  createUserByPassword:
    handler: src/lambda/auth/createUserByEmail.handler
    events:
      - http:
          method: post
          path: create
          cors: true
          authorizer: Auth
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
